### ISSUE TITLE
SUBTLETY - title name mixup

### ISSUE THREAD

**Issue by franfranfranfran** [leon511/prj-rev-bwfs-dasmoto#5]
https://github.com/leon511/prj-rev-bwfs-dasmoto/blob/master/Dasmoto_Art/index.html#L6

double check the name of the page in title. this info does show on the tab when you open the page in a browser, so its crucial that its accurate

**Comment by leon511** [comment]
Fixed

**Comment by leon511** [comment]
Fixed
