### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by franfranfranfran** [leon511/prj-rev-bwfs-dasmoto#6]
**GRADE**: Meets Expectations

**SUMMARY**: Good job on this project! Once the link to the h1 image is fixed, the site looks great. Throughout the html, you did an excellent job using relative file paths to link to your images. Also, great job keeping your project folder organized by using the resources, image, and css folders.

Behind the scenes, it is crucial to keep your code neat and properly indented. Clean, concise code becomes more and more crucial as your projects grow in size and complexity. Also, keep an eye out for unused bit throughout as they can only lead to confusion and frustration down the line. 

As a next step, try using divs and classes to reinforce the main content structure of the page. Sectioning off each content block will help with styling, readability, and creating a well-defined structure for the page.

Keep up the good work!

**Comment by leon511** [comment]
fixed title, relative paths, moved image to img folder, used body to describe the fonts
